apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gke-flask-frontend
  labels:
    app: gke-flask
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gke-flask
        tier: frontend
    spec:
      containers:
      - name: gke-flask-app
        image: gcr.io/nobjas-test-project-161209/gke-flask
        imagePullPolicy: Always
        env:
        - name: PROCESSES
          value: gkeflask
        ports:
        - name: http-server
          containerPort: 8080
